# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 783f6146d454cd08eb256ab7ec2b01c03ed21f7e7956f691a6cb035522cdc9f3034c7b932f5033c66f3fa83878d3458422fe3da4172476198f16d6d169a9b857

test:
  secret_key_base: c2318e6055848f3f5656d32db5a76aff1b4ea00ca2a5b704d65de8d5ff9f3ff3e13a0ce58c849f0b3f4ae2546d1a780236990c1399ae23ba9261b958bad931d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
